/**
 * @file optimo_controller/include/optimo_controller/workspace_hull.hpp
 * @brief Convex-hull workspace boundary for EE goal clamping.
 */
#pragma once

#include <string>

#include <Eigen/Dense>
#include <yaml-cpp/yaml.h>

namespace optimo_controller {

/**
 * @brief H-representation convex hull for EE workspace boundary.
 *
 * Loaded once at configure time from a YAML file generated by
 * scripts/compute_workspace.py.  Used in EETeleop::OneStep() to clamp
 * pos_goal_ to the kinematically reachable region every control tick.
 *
 * H-representation: for every face i,
 *   normals_.row(i).dot(p) + offsets_[i] <= 0   (point p is inside / on hull)
 */
class WorkspaceHull {
public:
  /**
   * @brief Load normals and offsets from a YAML file produced by compute_workspace.py.
   * @return true on success.
   */
  bool Load(const std::string& yaml_path) {
    try {
      const YAML::Node root = YAML::LoadFile(yaml_path);
      const auto& n_node = root["normals"];
      const auto& o_node = root["offsets"];
      if (!n_node || !o_node) return false;

      const std::size_t n_faces = n_node.size();
      if (n_faces == 0 || o_node.size() != n_faces) return false;

      normals_.resize(static_cast<Eigen::Index>(n_faces), 3);
      offsets_.resize(static_cast<Eigen::Index>(n_faces));

      for (std::size_t i = 0; i < n_faces; ++i) {
        const auto& row = n_node[i];
        normals_(static_cast<Eigen::Index>(i), 0) = row[0].as<double>();
        normals_(static_cast<Eigen::Index>(i), 1) = row[1].as<double>();
        normals_(static_cast<Eigen::Index>(i), 2) = row[2].as<double>();
        offsets_(static_cast<Eigen::Index>(i))    = o_node[i].as<double>();
      }
      loaded_ = true;
    } catch (...) {
      loaded_ = false;
    }
    return loaded_;
  }

  bool IsLoaded() const { return loaded_; }

  /**
   * @brief Returns true if p is inside (or on) the hull within tolerance.
   */
  bool Contains(const Eigen::Vector3d& p, double tol = 1e-6) const {
    return (normals_ * p + offsets_).maxCoeff() <= tol;
  }

  /**
   * @brief Clamp pos_goal after integrating a velocity command.
   *
   * Two sequential checks:
   *   1. Anti-windup: keep pos_goal within max_lookahead [m] of actual_ee_pos.
   *   2. Workspace boundary: project pos_goal back inside the hull if it escaped.
   *
   * @param pos_goal      Current integrated goal (in base frame).
   * @param actual_ee_pos Current actual EE position from FK (in base frame).
   * @param max_lookahead Anti-windup radius [m].  <= 0 to skip.
   * @return Clamped goal position.
   */
  Eigen::Vector3d Clamp(const Eigen::Vector3d& pos_goal,
                        const Eigen::Vector3d& actual_ee_pos,
                        double max_lookahead) const {
    Eigen::Vector3d result = pos_goal;

    // (1) Anti-windup: goal must stay within max_lookahead of actual.
    if (max_lookahead > 0.0) {
      const Eigen::Vector3d diff = result - actual_ee_pos;
      const double dist = diff.norm();
      if (dist > max_lookahead) {
        result = actual_ee_pos + diff * (max_lookahead / dist);
      }
    }

    // (2) Workspace boundary: single-face projection onto most-violated face.
    if (loaded_) {
      const Eigen::VectorXd violations = normals_ * result + offsets_;
      Eigen::Index max_idx = 0;
      const double max_viol = violations.maxCoeff(&max_idx);
      if (max_viol > 0.0) {
        result -= max_viol * normals_.row(max_idx).transpose();
      }
    }

    return result;
  }

private:
  Eigen::MatrixXd normals_;   // (n_faces × 3)
  Eigen::VectorXd offsets_;   // (n_faces,)
  bool loaded_{false};
};

}  // namespace optimo_controller
