dynamixel_topic_controller:
  ros__parameters:
    device_name: /dev/ttyUSB0
    baud_rate: 1000000
    protocol_version: 2.0
    dxl_id: 101
    torque_enable_address: 64
    operating_mode_address: 11
    goal_position_address: 116
    present_position_address: 132
    position_data_size: 4
    enable_torque_on_start: true
    disable_torque_on_shutdown: true
    set_operating_mode_on_start: false
    position_operating_mode: 3
    read_period_ms: 50
    position_min_rad: -3.141592653589793
    position_max_rad: 3.141592653589793
    position_min_tick: 0
    position_max_tick: 4095
    command_topic: ~/goal_position
    present_position_topic: ~/present_position
