offsets:
  - name: thumb_roll
    offset: 0
  - name: thumb_yaw
    offset: 0
  - name: thumb_mcp
    offset: -0.515945435
  - name: thumb_pip
    offset: 8.66693306
  - name: index_mcp
    offset: 5.60101509
  - name: index_pip
    offset: 7.20550156
  - name: middle_mcp
    offset: 0.10090065
  - name: middle_pip
    offset: 5.68188667
