/optimo/controller_manager:
  ros__parameters:
    update_rate: 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    wbc_controller:
      type: optimo_controller/OptimoController

/optimo/joint_state_broadcaster:
  ros__parameters:
    use_local_topics: true

/optimo/wbc_controller:
  ros__parameters:
    robot_prefix: "optimo_"
    robot_index: 0
    use_sim_hardware: false
