/**:
  ros__parameters:
    pid_gains:
      position:
        optimo_joint1:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 95.0
          u_clamp_min: -95.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint2:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 95.0
          u_clamp_min: -95.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint3:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 40.0
          u_clamp_min: -40.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint4:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 40.0
          u_clamp_min: -40.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint5:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 15.0
          u_clamp_min: -15.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint6:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 15.0
          u_clamp_min: -15.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint7:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 15.0
          u_clamp_min: -15.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
      velocity:
        optimo_joint1:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 95.0
          u_clamp_min: -95.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint2:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 95.0
          u_clamp_min: -95.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint3:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 40.0
          u_clamp_min: -40.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint4:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 40.0
          u_clamp_min: -40.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint5:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 15.0
          u_clamp_min: -15.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint6:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 15.0
          u_clamp_min: -15.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
        optimo_joint7:
          p: 0.0
          i: 0.0
          d: 0.0
          u_clamp_max: 15.0
          u_clamp_min: -15.0
          i_clamp_max: 0.0
          i_clamp_min: 0.0
          antiwindup_strategy: "none"
