# =============================================================
# Draco Task Pool
# =============================================================

task_pool:
  - name: "com_task"
    type: "ComTask"
    kp: [40, 40, 40]
    kd: [8, 8, 8]
    kp_ik: [1.0, 1.0, 1.0]
    weight: [50, 50, 50]

  - name: "jpos_task"
    type: "JointTask"
    kp: 30.0
    kd: 3.0
    kp_ik: 1.0
    weight: 1.0

  - name: "lfoot_force"
    type: "ForceTask"
    contact_name: "lfoot_contact"
    weight: [0, 0, 0, 0, 0, 0]

  - name: "rfoot_force"
    type: "ForceTask"
    contact_name: "rfoot_contact"
    weight: [0, 0, 0, 0, 0, 0]

contact_pool:
  - name: "lfoot_contact"
    type: "SurfaceContact"
    target_frame: "l_foot_contact"
    mu: 0.5
    foot_half_length: 0.10
    foot_half_width: 0.05

  - name: "rfoot_contact"
    type: "SurfaceContact"
    target_frame: "r_foot_contact"
    mu: 0.5
    foot_half_length: 0.10
    foot_half_width: 0.05
